import dynamic from "next/dynamic";
import type { PageBlocks } from "@/tina/__generated__/types";

// Statically import the Hero block as it is usually "above the fold"
import { HeroBlock } from "@/components/blocks/hero.block";

// Dynamically import all other blocks to code-split them.
// This means the browser only downloads the code for the blocks it needs to render.
const DynamicFeatureList = dynamic(() =>
  import("@/components/blocks/feature.block").then((mod) => mod.FeatureBlock)
);
// ... add all your other 50+ dynamic imports here

type BlockRendererProps = {
  block: PageBlocks; // This type is generated by TinaCMS and includes all possible blocks
};

export const BlockRenderer = ({ block }: BlockRendererProps) => {
  // Use a switch statement to determine which component to render.
  switch (block.__typename) {
    case "PageBlocksHero":
      return <HeroBlock {...block} />;

    case "PageBlocksFeatureList":
      return <DynamicFeatureList {...block} />;

    // ... add cases for all your other blocks here

    default:
      // It's good practice to return null for any unknown block type.
      // You can also add a console warning here for debugging.
      console.warn(`No component found for block type: ${block.__typename}`);
      return null;
  }
};
