import dynamic from "next/dynamic";
import type {
  PageBlocks,
  ServiceBlocks,
  ServiceConnection,
} from "@/tina/__generated__/types";

// Dynamically import all other blocks to code-split them.
// This means the browser only downloads the code for the blocks it needs to render.
const DynamicHero = dynamic(() =>
  import("@/components/blocks/hero.block").then((mod) => mod.default)
);
const DynamicFeatureList = dynamic(() =>
  import("@/components/blocks/feature.block").then((mod) => mod.default)
);
const DynamicServiceList = dynamic(() =>
  import("@/components/blocks/serviceList.block").then((mod) => mod.default)
);
// ... add all your other 50+ dynamic imports here

type BlockRendererProps = {
  block: PageBlocks | ServiceBlocks; // This type is generated by TinaCMS and includes all possible blocks
  services: { data: ServiceConnection | null };
};

const BlockRenderer = ({ block, services }: BlockRendererProps) => {
  // Use a switch statement to determine which component to render.
  switch (block.__typename) {
    // Page Blocks
    case "PageBlocksHero":
      return <DynamicHero {...block} />;

    case "PageBlocksFeatureList":
      return <DynamicFeatureList {...block} />;

    case "PageBlocksServiceList":
      return <DynamicServiceList {...block} services={services} />;

    // Service Blocks
    case "ServiceBlocksHero":
      return <DynamicHero {...block} />;

    case "ServiceBlocksFeatureList":
      return <DynamicFeatureList {...block} />;

    default:
      // It's good practice to return null for any unknown block type.
      // You can also add a console warning here for debugging.
      console.warn(`No component found for block type: ${block.__typename}`);
      return null;
  }
};

export default BlockRenderer;
